### PR TITLE
Added my name to the Web Development Section

### PR DESCRIPTION
**Pull request by Minty-cyber**

### CODE REVIEW

**Review by mesrenyamedogbe — CHANGES_REQUESTED** [review]
Hello @Minty-cyber could you kindly arrange the entry in alphabetical order? Thank you!

**Comment by Minty-cyber** [comment]
Alright sure I will do that soon

**Comment by mesrenyamedogbe** [comment]
Thank you!

**Comment by Minty-cyber** [comment]
I have done that now.

**Pull request closed without merging**
